### ISSUE TITLE
Exlude directories option

### ISSUE THREAD

**Issue by pyros2097** [liudng/dogo#10]
Is it possible to exclude certain directories? We have a node_modules directory and a vendor directory and these have a lot of files. Even putting a file extension as .go doensn't do much help.

**Comment by G07cha** [comment]
What expected in for this feature? Just basic support for excluding root folders or something more complicated such as `docs/**/*.md`? Can you define desired functionality?

**Comment by pyros2097** [comment]
Well there are many watches being created for all files in node_modules and vendor directory which seems like a waste of resource thats all and So I need to specify on the folders I use. For now I switched to nodemon.
