### ISSUE TITLE
Deleting source file causes infinite error

### ISSUE THREAD

**Issue by G07cha** [liudng/dogo#11]
Hi, "dogo" is really simplifying my workflow, thank you guys for creating and maintaining this utility but one thing makes me sad sometimes.

Let's say I have the following scenario:
1. Create new file(let's say "test.go")
2. Start "dogo"
3. Remove file

In result "dogo" will constantly log: `stat %filepath%: no such file or directory` and I need to restart in order to continue the auto build. I'm using the latest version on OS X El Capitan by the way.

**Comment by liudng** [comment]
dogo only monitor file modification event on mac osx. can not monitor the creation and deletion.
If I have a mac computer, will improve this feature.
If you can help me to improve it, please submit a pull request, be grateful.

**Comment by G07cha** [comment]
Hi, @liudng, thanks for a response. I'll be happy to implement this.

But I was thinking about replacing existing filesystem checks with [fsnotify](https://github.com/fsnotify/fsnotify) library which is a bridge for fs libraries for all platforms. What do you think about this? Or should I only update existing OS X code?

**Comment by liudng** [comment]
Update os x implementation first. Use fsnotify will be another architecture, May be implemented in future releases.
