### ISSUE TITLE
use DelayTime instead of Decreasing

### ISSUE THREAD

**Issue by zhangpy** [liudng/dogo#8]
I use sublime to edit my file. After I press ctr+s, sublime will format my file and save it again.
dogo will get two modify events and trigger 2 build and run. (because my app is web, it will report port is used error)
If dogo delay 0.5 second to build and run, there will be no such issue.
Maybe we don't need decreasing but just increase DelayTime, then we will not ignore any change.

**Comment by liudng** [comment]
Try increasing the value of Decreasing. Decreasing works only on Windows operating systems.

**Comment by zhangpy** [comment]
I only works on linux. but thanks for the reply.
