### ISSUE TITLE
Runcmd is launched with wrong working dir

### ISSUE THREAD

**Issue by joegalaxy71** [liudng/dogo#9]
Executable file should have working dir set to filepath.dir("[runcmd command]").
Why exist both "WorkingDir" and "SourceDir" if they must have the same value?
I use "go install" as build command and wouldn't want to switch to an arbitrary build.
(apart from issue it'a very useful utility)

**Comment by liudng** [comment]
WorkingDir and SourceDir are diffrent. 
WorkingDir for finding dojo.json or other miscellaneous files. It can be set to any path you want.
SourceDir is the location to be monitored. It is an array type.
